# Generated by Django 4.1.7 on 2023-02-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('class_times', models.ManyToManyField(related_name='Course', to='api.time')),
                ('exam_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='api.time')),
            ],
        ),
    ]
